//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA_PR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Jurnal = new HashSet<Jurnal>();
        }
    
        public int ID { get; set; }
        public Nullable<int> People { get; set; }
        public Nullable<int> TitleGroup { get; set; }
        public Nullable<int> Cours { get; set; }
    
        public virtual Cours Cours1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal> Jurnal { get; set; }
        public virtual People People1 { get; set; }
        public virtual StudentGroup StudentGroup { get; set; }
    }
}
